config/routes.rb
Rails.application.routes.draw do
  
  root(to: "static#home")
  
  resources :birthstones

  resources :profiles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/birthstone.rb
class Birthstone < ApplicationRecord
has_and_belongs_to_many :profiles
end

app/models/birthstones_profile.rb
class BirthstonesProfile < ApplicationRecord
  belongs_to :birthstone
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_and_belongs_to_many :birthstones
    validates :name, presence: true, length: {in: 1..25 }
    validates :birthdate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def home
       
    end
end

app/controllers/birthstones_controller.rb
class BirthstonesController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :find_profile, only: [:show, :edit, :update, :destroy ]  

    def index
    @profiles = Profile.all    
    end

    def show
    
    end

    def new
     @profile = Profile.new
    end

    def create
           @profile = Profile.new(profile_params)
        if @profile.save
           redirect_to profiles_path
        else
           flash.now[:error] = @profile.errors.full_messages
           render :new
    end

    def edit
        # @profile.name = ""
    end

    def update
        if @profile.update(profile_params)
           redirect_to profile_path(@profile)
        else 
            flash.now[:error] = @profile.errors.full_messages
            render :edit
        end
    end 

        def destroy
            @profile.destroy
            flash[:notice] = "#{@profile.name} was deleted"
            redirect_to profiles_path           
        end
end


     private

     def profile_params
        params.require(:profile).permit(:name, :birthdate)       
     end

     def find_profile
       @profile = Profile.find_by_id(params[:id])
     end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthstones_helper.rb
module BirthstonesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetToKnowMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <ul> 
        <li><%= link_to("Home", root_path) %></li>
        <li><%= link_to("Profile List", profiles_path) %></li>
        <li><%= link_to("New Profile", new_profile_path) %></li>
      </ul>
    </nav>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <p><%= error %></p>
        <% end %>
      <% end %>
      <%= content_tag("p", flash[:notice]) if flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<h1> Edit Profile </h1>

<%= form_for @profile do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :birthdate %>
        <%= f.date_field :birthdate %>
    </div>
    <%= f.submit "Edit Profile" %>
<% end %>

app/views/profiles/index.html.erb
<h1> All Profiles List </h1>

<ul> 
<% @profiles.each do |profile| %>
    <li><%= link_to profile.name, profile_path(profile) %></li>
<% end %>
</ul>

app/views/profiles/new.html.erb
<h1> Create Profile </h1>

<%= form_for @profile do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :birthdate %>
        <%= f.date_field :birthdate %>
    </div>
    <%= f.submit "Create Profile" %>
<% end %>

app/views/profiles/show.html.erb
<h1><%= @profile.name %></h1>
    <p>Birthdate: <%= @profile.birthdate %></p>
    <p>Astrological Zodiac Sign: <%= @profile.azodiac %></p>
    <p>Chinese Zodiac Sign: <%= @profile.czodiac %></p>
    <p>Life Path Number: <%= @profile.lifepathnumber %></p>
    <p>Birthstone: <%= @profile.birthstone %></p>
    <p>Lucky Flower: <%= @profile.luckyflower %></p>
    <p>Recomended Tea: <%= @profile.tea %></p>

    <%= link_to "Edit", edit_profile_path(@profile) %>
    <%= link_to "Delete", profile_path(@profile), method: "delete" %>